services:
  sokinqalb-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sokinqalb_web_app
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
