services:
  sokinqalb-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sokinqalb_web_app
    restart: always
    network_mode: "host"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
